Fix AttributeError: 'SolidLanguageServer' object has no attribute 'logger'
Bug introduced in commit f07ba2c (selectionRange support) after
LanguageServerLogger was removed in 82d495b.

Changes:
- Replace self.logger.log() with log.error() in request_selection_range()
- Replace self.logger.log() with log.debug() in request_containing_symbol()